BTN_FORGET = "Forget everything I told you 😉"
BTN_START_DIALOG = "Start a dialogue"
BTN_ADVICE_FOR_DAY = "Advice for the day 😇"
BTN_CHARGE_MOTIVATION = "Motivation boost 💪"
BTN_STOP = "Stop ⛔️"
BTN_DONATES = "Support the project 😎"
BTN_LISTEN = "Listen to me 🫂"